version: '3'
services:
  mongo:
    image: mongo:3.6.15-xenial
    volumes:
      - /volumes/mongo:/data/db
    restart: always
    network_mode: host
  postgres:
    image: postgres:12-alpine
    volumes:
      - /volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    network_mode: host
  mcxptt_coreservice:
    image: aleasrl/mcxptt_coreservice:1.5.4
    depends_on:
      - mongo
    volumes:
      - ${PWD}/config/services_configs.json:/home/mcs/config/services_configs.json
      - ${PWD}/files:/home/mcs/files
      - ${PWD}/config/proxy:/home/mcs/config/proxy
    restart: always
    network_mode: host
  mcxptt_idmsservice:
    image: aleasrl/mcxptt_idmsservice:1.5.4
    depends_on:
      - mongo
    volumes:
      - ${PWD}/config/services_configs.json:/home/mcs/config/services_configs.json
    restart: always
    network_mode: host
  mcxptt_filemanagerservice:
    image: aleasrl/mcxptt_filemanagerservice:1.5.1
    depends_on:
      - mongo
    volumes:
      - ${PWD}/config/services_configs.json:/home/mcs/config/services_configs.json
      - ${PWD}/files:/home/mcs/files
    restart: always
    network_mode: host  
  mcxptt_configurator:
    image: aleasrl/mcxptt_configurator:1.5.4_LDO_RC
    volumes:
      - ${PWD}/config/site_config.php:/var/www/mcptt.talkway.it/https/app/Config/custom_configurations.php
      - ${PWD}/config/proxy:/etc/apache2/proxy
      - ${PWD}/config/apache.conf:/etc/apache2/conf.d/zz_mcptt.talkway.it.conf
      - ${PWD}/config/certificates:/etc/apache2/certificates
    depends_on:
      - mcxptt_coreservice
    restart: always
    network_mode: host
  mcxptt_dispatcher:
    image: aleasrl/mcxptt_dispatcher:1.0.5_LDO_RC
    restart: always
    network_mode: host
