---
- name: remote operations
  hosts: all
  tasks:
    - name: read the content of dir /tmp/
      command: "ls -lah /tmp/"
      register: dir_out

    - debug: var={{item}}
      with_items: dir_out.stdout_lines

    - name: Creates directory
      file:
        path: ~/mcxptt_deploy_20F25_1145_LDO
        state: directory
        
    - name: Creates directory /licensemanager
      file:
        path: ~/mcxptt_deploy_20F25_1145_LDO/licensemanager
        state: directory
        
    - name: Creates directory /scripts
      file:
        path: ~/mcxptt_deploy_20F25_1145_LDO/scripts
        state: directory
        
###    - name: Copy in remote host file from /tmp/ to dir /root/demo_directory_created_through_awx
###      copy:
###        src: /tmp/mcxptt_deploy_20f25_1145_ldo.tgz
###        dest: ~/mcxptt_deploy_20F25_1145_LDO
###        remote_src: yes

    - name: Download dir licensemanager
      get_url:
        url: https://github.com/lucaspinacci41/MyProject/blob/master/licensemanager/mcpttlicensemanager_1_0_1_20F18_1214.tgz
        dest: ~/mcxptt_deploy_20F25_1145_LDO/licensemanager/

    - name: Download dir releasenotes
      get_url:
        url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/releasenotes
        dest: ~/mcxptt_deploy_20F25_1145_LDO/releasenotes/
        
    - name: Download dir scripts
      get_url:
        url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/scripts
        dest: ~/mcxptt_deploy_20F25_1145_LDO/scripts/       

    - name: Download file content.txt
      get_url:
        url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/content.txt
        dest: ~/mcxptt_deploy_20F25_1145_LDO  

    - name: Download file setup.sh
      get_url:
        url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/setup.sh
        dest: ~/mcxptt_deploy_20F25_1145_LDO  

###    - name: Execute the setup.sh
###      shell: ~/mcxptt_deploy_20F25_1145_LDO/setup.sh

###    - name: Copy from local /tmp/ to remote directoty
###      copy:
###        src: ~/prova/prova.txt
###        dest: ~/demo_directory_created_through_awx
###        remote_src: no

###    - name: Store remote file into /tmp/
###      fetch:
###        src: /tmp/yum.log
###        dest: /tmp/     
###   - name: Delete directory
###     file:
###       path: ~/demo_directory_created_through_awx
###       state: absent
