- name: create_directory
  hosts: all
  tasks:

   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory
   - name: Delete directory
     file:
       path: ~/demo_directory_created_through_awx
       state: absent
