- name: create_directory
  hosts: all
  tasks:
   - command: "ls -lah /tmp/"
     register: dir_out

   - debug: var={{item}}
     with_items: dir_out.stdout_lines

   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory
       
   - name: Copy local file /root/get-pip.py in remote dir /root/demo_directory_created_through_awx
     copy:
       src: ~/tmp/prova.txt
       dest: ~/demo_directory_created_through_awx/prova.sh
       remote_src: False
       
###   - name: Delete directory
###     file:
###       path: ~/demo_directory_created_through_awx
###       state: absent
