- name: create_directory
  hosts: all
  tasks:
   - command: "ls -lah /tmp/"
     register: dir_out

   - debug: var={{item}}
     with_items: dir_out.stdout_lines

   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory
       
   - name: Copy local file to dir /root/demo_directory_created_through_awx
     copy:
       src: /tmp/mcxptt_deploy_20f25_1145_ldo.tgz
       dest: ~/demo_directory_created_through_awx/prova.sh
       remote_src: no
       
###   - name: Delete directory
###     file:
###       path: ~/demo_directory_created_through_awx
###       state: absent
