- name: create_directory
  hosts: all
  tasks:

   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory
   - name: Copy local file /root/get-pip.py in remote dir /root/demo_directory_created_through_awx
     copy:
       src: /root/prova.sh
       dest: ~/demo_directory_created_through_awx/get-pip.py
       mode: u+rw,g-wx,o-rwx
###   - name: Delete directory
###     file:
###       path: ~/demo_directory_created_through_awx
###       state: absent
