---
- name: remote operations
  hosts: all
  vars:
    deploy: mcxptt_deploy_20F25_1145_LDO
  tasks:
  - name: Creates deployment directory on target host
    file:
      path: ~/{{ deploy }}
      state: directory
        
  - name: Creates subdirectory /licensemanager on target host
    file:
      path: ~/{{ deploy }}/licensemanager
      state: directory
        
  - name: Creates subdirectory /scripts on target host
    file:
      path: ~/"{{ deploy }}"/scripts
      state: directory

  - name: Download licensemanager on target host
    get_url:
      url: https://github.com/lucaspinacci41/MyProject/blob/master/licensemanager/mcpttlicensemanager_1_0_1_20F18_1214.tgz
      dest: ~/"{{ deploy }}"/licensemanager/

  - name: Download dir releasenotes
    get_url:
      url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/releasenotes
      dest: ~/"{{ deploy }}"/releasenotes/
        
  - name: Download dir scripts
    get_url:
      url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/scripts
      dest: ~/"{{ deploy }}"/scripts/       

  - name: Download file content.txt
    get_url:
      url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/content.txt
      dest: ~/"{{ deploy }}"
      
  - name: Download file setup.sh
    get_url:
      url: https://raw.githubusercontent.com/lucaspinacci41/MyProject/master/setup.sh
      dest: ~/"{{ deploy }}"  

###    - name: read the content of dir /tmp/
###      command: "ls -lah /tmp/"
###      register: dir_out

###    - name: Copy in remote host file from /tmp/ to dir /root/demo_directory_created_through_awx
###      copy:
###        src: /tmp/mcxptt_deploy_20f25_1145_ldo.tgz
###        dest: ~/"{{ item }}"
###        remote_src: yes

###    - name: Execute the setup.sh
###      shell: ~/"{{ item }}"/setup.sh

###    - name: Copy from local /tmp/ to remote directoty
###      copy:
###        src: ~/prova/prova.txt
###        dest: ~/demo_directory_created_through_awx
###        remote_src: no

###    - name: Store remote file into /tmp/
###      fetch:
###        src: /tmp/yum.log
###        dest: /tmp/     
###   - name: Delete directory
###     file:
###       path: ~/demo_directory_created_through_awx
###       state: absent
